create table "news_feed_items" (
  "id" bigint generated by default as identity primary key,
  "author" text,
  "role" text,
  "avatar" text,
  "content" text,
  "time" text,
  "source" text,
  "link" text,
  "date" date not null,
  "inserted_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);
