create table "news_feed_items" (
  "id" bigint generated by default as identity primary key,
  "author" text,
  "role" text,
  "avatar" text,
  "content" text,
  "time" text,
  "source" text,
  "link" text,
  "date" date not null,
  "inserted_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table "news_feed_items" enable row level security;

drop policy if exists "Authenticated users can read news feed items" on "news_feed_items";
create policy "Authenticated users can read news feed items"
  on "news_feed_items"
  for select
  to authenticated
  using (true);
