create table "news_feed_items" (
  "id" bigint generated by default as identity primary key,
  "author" text not null,
  "role" text not null,
  "avatar" text,
  "content" text not null,
  "time" text default 'Recently',
  "source" text not null,
  "link" text,
  "date" date not null default current_date,
  "is_direct_from_source" boolean not null default false,
  "inserted_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table "news_feed_items" enable row level security;

drop policy if exists "Authenticated users can read news feed items" on "news_feed_items";
create policy "Authenticated users can read news feed items"
  on "news_feed_items"
  for select
  to authenticated
  using (true);
