create table "ticker_feed_items" (
  "id" bigint generated by default as identity primary key,
  "type" text not null,
  "content" text not null,
  "date" date not null,
  "inserted_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table "ticker_feed_items" enable row level security;

drop policy if exists "Authenticated users can read ticker feed items" on "ticker_feed_items";
create policy "Authenticated users can read ticker feed items"
  on "ticker_feed_items"
  for select
  to authenticated
  using (true);
