create table "ticker_feed_items" (
  "id" bigint generated by default as identity primary key,
  "type" text,
  "text" text,
  "date" date,
  "inserted_at" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updated_at" timestamp with time zone default timezone('utc'::text, now()) not null
);
