
  create table "public"."news_feed_items" (
    "id" bigint generated by default as identity not null,
    "author" text,
    "role" text,
    "avatar" text,
    "content" text,
    "time" text,
    "source" text,
    "link" text,
    "date" date not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );



  create table "public"."ticker_feed_items" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "text" text,
    "date" date not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );



  create table "public"."user_profiles" (
    "user_id" uuid not null,
    "first_name" text,
    "last_name" text,
    "payment_status" text not null default 'unpaid'::text,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."user_profiles" enable row level security;

CREATE UNIQUE INDEX news_feed_items_pkey ON public.news_feed_items USING btree (id);

CREATE UNIQUE INDEX ticker_feed_items_pkey ON public.ticker_feed_items USING btree (id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (user_id);

alter table "public"."news_feed_items" add constraint "news_feed_items_pkey" PRIMARY KEY using index "news_feed_items_pkey";

alter table "public"."ticker_feed_items" add constraint "ticker_feed_items_pkey" PRIMARY KEY using index "ticker_feed_items_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_payment_status_check" CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'past_due'::text, 'canceled'::text]))) not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_payment_status_check";

alter table "public"."user_profiles" add constraint "user_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.user_profiles (user_id, first_name, last_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name'
  )
  on conflict (user_id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_user_payment_claims()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update auth.users
  set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
    || jsonb_build_object(
      'payment_status', new.payment_status,
      'paid', (new.payment_status = 'paid')
    )
  where id = new.user_id;

  return new;
end;
$function$
;

grant delete on table "public"."news_feed_items" to "anon";

grant insert on table "public"."news_feed_items" to "anon";

grant references on table "public"."news_feed_items" to "anon";

grant select on table "public"."news_feed_items" to "anon";

grant trigger on table "public"."news_feed_items" to "anon";

grant truncate on table "public"."news_feed_items" to "anon";

grant update on table "public"."news_feed_items" to "anon";

grant delete on table "public"."news_feed_items" to "authenticated";

grant insert on table "public"."news_feed_items" to "authenticated";

grant references on table "public"."news_feed_items" to "authenticated";

grant select on table "public"."news_feed_items" to "authenticated";

grant trigger on table "public"."news_feed_items" to "authenticated";

grant truncate on table "public"."news_feed_items" to "authenticated";

grant update on table "public"."news_feed_items" to "authenticated";

grant delete on table "public"."news_feed_items" to "service_role";

grant insert on table "public"."news_feed_items" to "service_role";

grant references on table "public"."news_feed_items" to "service_role";

grant select on table "public"."news_feed_items" to "service_role";

grant trigger on table "public"."news_feed_items" to "service_role";

grant truncate on table "public"."news_feed_items" to "service_role";

grant update on table "public"."news_feed_items" to "service_role";

grant delete on table "public"."ticker_feed_items" to "anon";

grant insert on table "public"."ticker_feed_items" to "anon";

grant references on table "public"."ticker_feed_items" to "anon";

grant select on table "public"."ticker_feed_items" to "anon";

grant trigger on table "public"."ticker_feed_items" to "anon";

grant truncate on table "public"."ticker_feed_items" to "anon";

grant update on table "public"."ticker_feed_items" to "anon";

grant delete on table "public"."ticker_feed_items" to "authenticated";

grant insert on table "public"."ticker_feed_items" to "authenticated";

grant references on table "public"."ticker_feed_items" to "authenticated";

grant select on table "public"."ticker_feed_items" to "authenticated";

grant trigger on table "public"."ticker_feed_items" to "authenticated";

grant truncate on table "public"."ticker_feed_items" to "authenticated";

grant update on table "public"."ticker_feed_items" to "authenticated";

grant delete on table "public"."ticker_feed_items" to "service_role";

grant insert on table "public"."ticker_feed_items" to "service_role";

grant references on table "public"."ticker_feed_items" to "service_role";

grant select on table "public"."ticker_feed_items" to "service_role";

grant trigger on table "public"."ticker_feed_items" to "service_role";

grant truncate on table "public"."ticker_feed_items" to "service_role";

grant update on table "public"."ticker_feed_items" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";


  create policy "Users can update own basic profile fields"
  on "public"."user_profiles"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check (((auth.uid() = user_id) AND (payment_status = ( SELECT up.payment_status
   FROM public.user_profiles up
  WHERE (up.user_id = auth.uid())))));



  create policy "Users can view own profile"
  on "public"."user_profiles"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));


CREATE TRIGGER on_user_profile_payment_status_changed AFTER UPDATE OF payment_status ON public.user_profiles FOR EACH ROW WHEN ((old.payment_status IS DISTINCT FROM new.payment_status)) EXECUTE FUNCTION public.sync_user_payment_claims();

CREATE TRIGGER on_auth_user_created_user_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_profile();


