
  create table "public"."news_feed_items" (
    "id" bigint generated by default as identity not null,
    "author" text,
    "role" text,
    "avatar" text,
    "content" text,
    "time" text,
    "source" text,
    "date" date,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );



  create table "public"."ticker_feed_items" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "text" text,
    "date" date,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


CREATE UNIQUE INDEX news_feed_items_pkey ON public.news_feed_items USING btree (id);

CREATE UNIQUE INDEX ticker_feed_items_pkey ON public.ticker_feed_items USING btree (id);

alter table "public"."news_feed_items" add constraint "news_feed_items_pkey" PRIMARY KEY using index "news_feed_items_pkey";

alter table "public"."ticker_feed_items" add constraint "ticker_feed_items_pkey" PRIMARY KEY using index "ticker_feed_items_pkey";

grant delete on table "public"."news_feed_items" to "anon";

grant insert on table "public"."news_feed_items" to "anon";

grant references on table "public"."news_feed_items" to "anon";

grant select on table "public"."news_feed_items" to "anon";

grant trigger on table "public"."news_feed_items" to "anon";

grant truncate on table "public"."news_feed_items" to "anon";

grant update on table "public"."news_feed_items" to "anon";

grant delete on table "public"."news_feed_items" to "authenticated";

grant insert on table "public"."news_feed_items" to "authenticated";

grant references on table "public"."news_feed_items" to "authenticated";

grant select on table "public"."news_feed_items" to "authenticated";

grant trigger on table "public"."news_feed_items" to "authenticated";

grant truncate on table "public"."news_feed_items" to "authenticated";

grant update on table "public"."news_feed_items" to "authenticated";

grant delete on table "public"."news_feed_items" to "service_role";

grant insert on table "public"."news_feed_items" to "service_role";

grant references on table "public"."news_feed_items" to "service_role";

grant select on table "public"."news_feed_items" to "service_role";

grant trigger on table "public"."news_feed_items" to "service_role";

grant truncate on table "public"."news_feed_items" to "service_role";

grant update on table "public"."news_feed_items" to "service_role";

grant delete on table "public"."ticker_feed_items" to "anon";

grant insert on table "public"."ticker_feed_items" to "anon";

grant references on table "public"."ticker_feed_items" to "anon";

grant select on table "public"."ticker_feed_items" to "anon";

grant trigger on table "public"."ticker_feed_items" to "anon";

grant truncate on table "public"."ticker_feed_items" to "anon";

grant update on table "public"."ticker_feed_items" to "anon";

grant delete on table "public"."ticker_feed_items" to "authenticated";

grant insert on table "public"."ticker_feed_items" to "authenticated";

grant references on table "public"."ticker_feed_items" to "authenticated";

grant select on table "public"."ticker_feed_items" to "authenticated";

grant trigger on table "public"."ticker_feed_items" to "authenticated";

grant truncate on table "public"."ticker_feed_items" to "authenticated";

grant update on table "public"."ticker_feed_items" to "authenticated";

grant delete on table "public"."ticker_feed_items" to "service_role";

grant insert on table "public"."ticker_feed_items" to "service_role";

grant references on table "public"."ticker_feed_items" to "service_role";

grant select on table "public"."ticker_feed_items" to "service_role";

grant trigger on table "public"."ticker_feed_items" to "service_role";

grant truncate on table "public"."ticker_feed_items" to "service_role";

grant update on table "public"."ticker_feed_items" to "service_role";


